config:
  aws:region: eu-central-1
  # only applicable for Patrik Simms
  aws:profile: private
  bitcoin-guesser-infra:dbPassword:
  # https://www.pulumi.com/docs/iac/concepts/secrets/#committing-configuration-to-source-control
    secure: AAABAJMnVGQd53v2URYs71pfWFBP+HwpjYJ7LGQns62nW9EpGfCJRH4TYDCx1UIinV+Blhzz7dcOtQ==
  bitcoin-guesser-infra:dockerImage: patriksimms1/bitcoin-guesser:ad712efb2358cbdc8dc81b2e8a7b2c05ecf98844

