config:
  aws:region: eu-central-1
  aws:profile: private
  bitcoin-guesser-infra:dbPassword:
    secure: AAABAJMnVGQd53v2URYs71pfWFBP+HwpjYJ7LGQns62nW9EpGfCJRH4TYDCx1UIinV+Blhzz7dcOtQ==
  bitcoin-guesser-infra:dockerImage: patriksimms1/bitcoin-guesser:b2b391f069c2bab31c965cb8e45f0bcb9eecc8f1

