ARG BUN_VERSION=1.2.21
FROM oven/bun:${BUN_VERSION}-alpine as builder

ARG WORKDIR_ENV
WORKDIR ${WORKDIR_ENV}

COPY public ./public
COPY src ./src
COPY index.html .
COPY tsconfig.json .
COPY tsconfig.node.json .
COPY vite.config.ts .
COPY ../tsconfig.json ..

ARG VITE_BITCOIN_GUESSER_BASE
ARG VITE_NODE_ENV

COPY package.json bun.lock components.json tsconfig.* ./
RUN bun install

CMD ["bun", "run", "dev"]

