/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gohar.Munir (https://sketchfab.com/Gohar.Munir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-bitcoin-ec0b85df2dde42eda90b571c12a7cd47
Title: Low Poly Bitcoin
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'

export function BitcoinModel() {
    const { nodes, materials } = useGLTF('/scene.gltf')
    const coinRef = useRef(null)
    const btcRef = useRef(null)

    useFrame((state, delta) => { 
        coinRef.current.rotation.y += delta
        btcRef.current.rotation.y += delta
    })

    return (
        <group dispose={null} scale={0.03}>
            <mesh
                ref={coinRef}
                castShadow
                receiveShadow
                geometry={nodes.BitCoin_LowPoly_FFC107_0.geometry}
                material={materials.FFC107}
            />
            <mesh
                ref={btcRef}
                castShadow
                receiveShadow
                geometry={nodes.BitCoin_LowPoly_FFFFFF_0.geometry}
                material={materials.FFFFFF}
            />
        </group>
    )
}

useGLTF.preload('/scene.gltf')
