/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gohar.Munir (https://sketchfab.com/Gohar.Munir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-bitcoin-ec0b85df2dde42eda90b571c12a7cd47
Title: Low Poly Bitcoin
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'

export function BitcoinModel() {
    const { nodes, materials } = useGLTF('/scene.gltf')
    const coinRef = useRef(null)
    const btcRef = useRef(null)

    useFrame((_state, delta) => { 
        if (coinRef !== null && btcRef !== null) {
            // TODO add types
            // @ts-expect-error mesh node is still untyped
            coinRef.current!.rotation.y += delta
            // @ts-expect-error mesh node is still untyped
            btcRef.current!.rotation.y += delta
        }
    })

    return (
        <group dispose={null} scale={0.03}>
            <mesh
                ref={coinRef}
                castShadow
                receiveShadow
                // @ts-expect-error node with index type has no further types since it depends on gltf file
                geometry={nodes['BitCoin_LowPoly_FFC107_0'].geometry}
                // @ts-expect-error same for material
                material={materials.FFC107}
            />
            <mesh
                ref={btcRef}
                castShadow
                receiveShadow
                // @ts-expect-error node with index type has no further types since it depends on gltf file
                geometry={nodes['BitCoin_LowPoly_FFFFFF_0'].geometry}
                // @ts-expect-error same for material
                material={materials.FFFFFF}
            />
        </group>
    )
}

useGLTF.preload('/scene.gltf')
