# .github/workflows/ci.yml
name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Bun 
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: cd frontend

      - name: Test where I am
        run: pwd

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test
